# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    language_version: python3.9

- repo: https://github.com/pycqa/flake8.git
  rev: 6.0.0
  hooks:
  - id: flake8
    args:
    - "--ignore=E501,E722,E203,W503,F403,F405"
    additional_dependencies:
    - flake8-black>=0.1.1

# - repo: local
#   hooks:
#   - id: unittests
#     name: run unit tests
#     entry: coverage run --include="src/wstore/*" --omit="__*__" src/manage.py test
#     language: system
#     pass_filenames: false


